name: Rspec and Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [2.5, 2.6, 2.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Test with Rspec
      run: |
          bundle exec rspec --format documentation --require spec_helper
  release:
    if: github.event_name == 'push'
    needs: rspec
    runs-on: ubuntu-latest
    env:
      BUNDLE_DEPLOYMENT: true
    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Zip
      run : |
        zip -r yq.zip ./*
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_TOKEN }}
      with:
        semantic_version: 17
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          semantic-release-rubygem
